theme: jekyll-theme-tactile
title: Ulyhmyges's homepage
description: Some description here...
logo: ./assets/clear.png
toto: View some text

github:
  public: yes
  is_project_page: yes
  repository_url: https://github.com/ulyhmyges/ulyhmyges.github.io
  repository_nwo: ""
