theme: jekyll-theme-minimal
title: Ulyhmyges's homepage
description: Bookmark this to keep an eye on my project updates!
logo: ./assets/clear.png
github:
  is_project_page: yes
  repository_url: https://github.com/ulyhmyges/ulyhmyges.github.io

