theme: jekyll-theme-tactile
title: Code, tapping and carriage return
description: Welcome to my tiny space, explore my work
logo: ./assets/clear.png
toto: View some text

github:
  public: yes
  is_project_page: yes
  repository_url: https://github.com/ulyhmyges/ulyhmyges.github.io
  repository_nwo: ""
  fx:
    repository_url: https://github.com/ulyhmyges/FX-Market-Data-API
    webserver_url: http://141.253.124.101:8088/

